[package]
name = "streamweave-kafka"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true
repository = "https://github.com/Industrial/streamweave/tree/main/packages/kafka"
homepage.workspace = true
documentation.workspace = true
keywords.workspace = true
categories.workspace = true
description = "Kafka producer and consumer for StreamWeave"

[features]
default = ["kafka"]
kafka = ["dep:rdkafka"]

[dependencies]
chrono = { workspace = true }
async-stream = { workspace = true }
streamweave = { path = "../streamweave" }
rdkafka = { workspace = true, optional = true }
serde = { workspace = true }
tokio = { workspace = true, features = ["macros", "rt", "full"] }
futures = { workspace = true }
async-trait = { workspace = true }
thiserror = { workspace = true }
tracing = { workspace = true }
serde_json = { workspace = true }

[dev-dependencies.proptest]
workspace = true
