[package]
name = "kafka"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true
repository.workspace = true
homepage.workspace = true
documentation.workspace = true
keywords.workspace = true
categories.workspace = true
description = "Kafka producer and consumer for StreamWeave"

[features]
default = ["kafka"]
kafka = ["dep:rdkafka"]
message-envelope = ["dep:streamweave-message"]

[dependencies.chrono]
workspace = true

[dependencies.async-stream]
workspace = true

[dependencies.streamweave]
path = "../streamweave"
version = "0.3.0"

[dependencies.streamweave-error]
path = "../error"
version = "0.3.0"

[dependencies.streamweave-message]
path = "../message"
version = "0.3.0"
optional = true

[dependencies.rdkafka]
workspace = true
optional = true

[dependencies.serde]
workspace = true

[dependencies.tokio]
workspace = true
features = ["macros", "rt", "full"]

[dependencies.futures]
workspace = true

[dependencies.async-trait]
workspace = true

[dependencies.thiserror]
workspace = true

[dependencies.tracing]
workspace = true

[dependencies.serde_json]
workspace = true

[dev-dependencies.proptest]
workspace = true
