[package]
name = "streamweave-producer-database"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true
repository.workspace = true
homepage.workspace = true
documentation.workspace = true
keywords.workspace = true
categories.workspace = true
description = "Database producer for StreamWeave"

[dependencies]
chrono = { workspace = true }
async-stream = { workspace = true }
streamweave = { path = "../../streamweave" }
streamweave-error = { path = "../../error" }
streamweave-message = { path = "../../message", optional = true }
sqlx = { workspace = true, optional = true, features = [
  "postgres",
  "mysql",
  "sqlite",
  "runtime-tokio-native-tls",
] }
serde = { workspace = true }
serde_json = { workspace = true }
base64 = "0.22"
tokio = { workspace = true, features = ["macros", "rt", "full"] }
futures = { workspace = true }
async-trait = { workspace = true }
thiserror = { workspace = true }
tracing = { workspace = true }

[features]
default = ["database"]
database = ["dep:sqlx"]
message-envelope = ["dep:streamweave-message"]
