[package]
name = "wasm-nodejs-example"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[dependencies]
streamweave = { path = "../../", features = ["wasm"], default-features = false }
wasm-bindgen = "0.2"

