[package]
name = "streamweave-metrics"
version = "0.3.0"
edition.workspace = true
authors.workspace = true
license.workspace = true
repository = "https://github.com/Industrial/streamweave/tree/main/packages/metrics"
homepage.workspace = true
documentation.workspace = true
keywords.workspace = true
categories.workspace = true
description = "Metrics collection for StreamWeave"

[dependencies]
streamweave = { path = "../streamweave", version = "0.3.0" }
tokio = { workspace = true, features = ["macros", "rt"] }
serde = { workspace = true }
serde_json = { workspace = true }
chrono = { workspace = true }
opentelemetry = { workspace = true, optional = true }
opentelemetry_sdk = { workspace = true, optional = true }
opentelemetry-otlp = { workspace = true, optional = true, features = [
  "grpc-tonic",
] }

[features]
default = []
prometheus = []
opentelemetry = [
  "dep:opentelemetry",
  "dep:opentelemetry_sdk",
  "dep:opentelemetry-otlp",
]
