[package]
name = "streamweave-database"
version = "0.4.0"
edition.workspace = true
authors.workspace = true
license.workspace = true
repository = "https://github.com/Industrial/streamweave/tree/main/packages/database"
homepage.workspace = true
documentation.workspace = true
keywords.workspace = true
categories.workspace = true
description = "Base types for StreamWeave database packages"

[dependencies]
serde = { workspace = true }
serde_json = { workspace = true }

[features]
default = []
message-envelope = ["dep:streamweave-message"]

[dependencies.streamweave-message]
path = "../message"
version = "0.4.0"
optional = true
