[package]
name = "streamweave-jsonl"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true
repository = "https://github.com/Industrial/streamweave/tree/main/packages/jsonl"
homepage.workspace = true
documentation.workspace = true
keywords.workspace = true
categories.workspace = true
description = "Jsonl producer and consumer for StreamWeave"

[features]
default = []
message-envelope = ["dep:streamweave-message"]

[dependencies.chrono]
workspace = true

[dependencies.async-stream]
workspace = true

[dependencies.streamweave]
path = "../streamweave"
version = "0.3.0"

[dependencies.streamweave-error]
path = "../error"
version = "0.3.0"

[dependencies.streamweave-message]
path = "../message"
version = "0.3.0"
optional = true

[dependencies.serde]
workspace = true

[dependencies.serde_json]
workspace = true

[dependencies.tokio]
workspace = true
features = ["macros", "rt", "fs", "io-util"]

[dependencies.tokio-stream]
workspace = true

[dependencies.futures]
workspace = true

[dependencies.async-trait]
workspace = true

[dependencies.thiserror]
workspace = true

[dependencies.tracing]
workspace = true

[dev-dependencies.tempfile]
workspace = true

[dev-dependencies.proptest]
workspace = true
