[package]
name = "streamweave-jsonl"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true
repository = "https://github.com/Industrial/streamweave/tree/main/packages/jsonl"
homepage.workspace = true
documentation.workspace = true
keywords.workspace = true
categories.workspace = true
description = "Jsonl producer and consumer for StreamWeave"

[features]
default = []

[dependencies]
chrono = { workspace = true }
async-stream = { workspace = true }
streamweave = { path = "../streamweave" }
serde = { workspace = true }
serde_json = { workspace = true }
tokio = { workspace = true, features = ["macros", "rt", "fs", "io-util"] }
tokio-stream = { workspace = true }
futures = { workspace = true }
async-trait = { workspace = true }
thiserror = { workspace = true }
tracing = { workspace = true }

[dev-dependencies.tempfile]
workspace = true

[dev-dependencies.proptest]
workspace = true
