[package]
name = "streamweave-process"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true
repository = "https://github.com/Industrial/streamweave/tree/main/packages/process"
homepage.workspace = true
documentation.workspace = true
keywords.workspace = true
categories.workspace = true
description = "Process management for StreamWeave"

[dependencies]
chrono = { workspace = true }
streamweave = { path = "../streamweave" }
streamweave-error = { path = "../error" }
streamweave-message = { path = "../message", optional = true }
tokio = { workspace = true, features = ["macros", "rt", "process", "io-util"] }
futures = { workspace = true }
async-stream = { workspace = true }
async-trait = { workspace = true }
thiserror = { workspace = true }
tracing = { workspace = true }

[dev-dependencies]
proptest = { workspace = true }

[features]
default = []
message-envelope = ["dep:streamweave-message"]
