[package]
name = "streamweave-array"
version = "0.6.0"
edition.workspace = true
authors.workspace = true
license.workspace = true
repository = "https://github.com/Industrial/streamweave/tree/main/packages/array"
homepage.workspace = true
documentation.workspace = true
keywords.workspace = true
categories.workspace = true
description = "Array producer and consumer for StreamWeave"

[features]
default = []
message-envelope = ["dep:streamweave-message"]

[dependencies.chrono]
workspace = true

[dependencies.streamweave]
path = "../streamweave"
version = "0.6.0"

[dependencies.streamweave-error]
path = "../error"
version = "0.6.0"

[dependencies.streamweave-message]
path = "../message"
version = "0.6.0"
optional = true

[dependencies.tokio]
workspace = true
features = ["macros", "rt"]

[dependencies.futures]
workspace = true

[dependencies.async-trait]
workspace = true

[dependencies.thiserror]
workspace = true

[dependencies.tracing]
workspace = true

[dev-dependencies]
proptest.workspace = true
streamweave-pipeline = { path = "../pipeline", version = "0.6.0" }
streamweave-transformers = { path = "../transformers", version = "0.6.0" }
streamweave-vec = { path = "../vec", version = "0.6.0" }
tokio = { workspace = true, features = ["macros", "rt", "test-util"] }
