[package]
name = "streamweave-database-mysql"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true
repository = "https://github.com/Industrial/streamweave/tree/main/packages/database-mysql"
homepage.workspace = true
documentation.workspace = true
keywords.workspace = true
categories.workspace = true
description = "MySQL producer and consumer for StreamWeave"

[dependencies]
base64 = "0.22"
chrono = { workspace = true }
async-stream = { workspace = true }
streamweave = { path = "../streamweave" }
streamweave-error = { path = "../error" }
streamweave-database = { path = "../database" }
streamweave-message = { path = "../message", optional = true }
sqlx = { workspace = true, features = ["mysql", "runtime-tokio-native-tls"] }
serde = { workspace = true }
serde_json = { workspace = true }
tokio = { workspace = true, features = ["macros", "rt", "full"] }
futures = { workspace = true }
async-trait = { workspace = true }
thiserror = { workspace = true }
tracing = { workspace = true }

[features]
default = []
message-envelope = ["dep:streamweave-message"]
