[package]
name = "streamweave-redis"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true
repository = "https://github.com/Industrial/streamweave/tree/main/packages/redis"
homepage.workspace = true
documentation.workspace = true
keywords.workspace = true
categories.workspace = true
description = "Redis producer and consumer for StreamWeave"

[features]
default = ["redis"]
redis = ["dep:redis"]
message-envelope = ["dep:streamweave-message"]

[dependencies]
chrono = { workspace = true }
async-stream = { workspace = true }
streamweave = { path = "../streamweave" }
streamweave-error = { path = "../error" }
streamweave-message = { path = "../message", optional = true }
redis = { workspace = true, optional = true, features = [
  "tokio-comp",
  "connection-manager",
] }
serde = { workspace = true }
serde_json = { workspace = true }
tokio = { workspace = true, features = ["macros", "rt", "full"] }
futures = { workspace = true }
async-trait = { workspace = true }
thiserror = { workspace = true }
tracing = { workspace = true }

[dev-dependencies.proptest]
workspace = true
