[package]
name = "streamweave-redis"
version = "0.4.0"
edition.workspace = true
authors.workspace = true
license.workspace = true
repository = "https://github.com/Industrial/streamweave/tree/main/packages/redis"
homepage.workspace = true
documentation.workspace = true
keywords.workspace = true
categories.workspace = true
description = "Redis producer and consumer for StreamWeave"

[features]
default = ["redis"]
redis = ["dep:redis"]
message-envelope = ["dep:streamweave-message"]

[dependencies.chrono]
workspace = true

[dependencies.async-stream]
workspace = true

[dependencies.streamweave]
path = "../streamweave"
version = "0.4.0"

[dependencies.streamweave-error]
path = "../error"
version = "0.4.0"

[dependencies.streamweave-message]
path = "../message"
version = "0.4.0"
optional = true

[dependencies.redis]
workspace = true
optional = true
features = ["tokio-comp", "connection-manager"]

[dependencies.serde]
workspace = true

[dependencies.serde_json]
workspace = true

[dependencies.tokio]
workspace = true
features = ["macros", "rt", "full"]

[dependencies.futures]
workspace = true

[dependencies.async-trait]
workspace = true

[dependencies.thiserror]
workspace = true

[dependencies.tracing]
workspace = true

[dev-dependencies.proptest]
workspace = true
