[package]
name = "streamweave-command"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true
repository = "https://github.com/Industrial/streamweave/tree/main/packages/command"
homepage.workspace = true
documentation.workspace = true
keywords.workspace = true
categories.workspace = true
description = "Command producer and consumer for StreamWeave"

[features]
default = []

[dependencies]
chrono = { workspace = true }
async-stream = { workspace = true }
streamweave = { path = "../streamweave" }
tokio = { workspace = true, features = ["macros", "rt", "process", "io-util"] }
futures = { workspace = true }
async-trait = { workspace = true }
thiserror = { workspace = true }
tracing = { workspace = true }

[dev-dependencies.proptest]
workspace = true
