[package]
name = "streamweave-pipeline"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true
repository = "https://github.com/Industrial/streamweave/tree/main/packages/pipeline"
homepage.workspace = true
documentation.workspace = true
keywords.workspace = true
categories.workspace = true
description = "Pipeline API for StreamWeave"

[dependencies]
streamweave = { path = "../streamweave" }
streamweave-error = { path = "../error" }
tokio = { workspace = true, features = ["macros", "rt"] }
futures = { workspace = true }

[dev-dependencies]
proptest = { workspace = true }
async-trait = { workspace = true }
streamweave-array = { path = "../array" }
streamweave-transformers = { path = "../transformers" }
streamweave-vec = { path = "../vec" }
tokio = { workspace = true, features = ["macros", "rt", "test-util"] }

[features]
