[package]
name = "streamweave-visualization"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true
repository = "https://github.com/Industrial/streamweave/tree/main/packages/visualization"
homepage.workspace = true
documentation.workspace = true
keywords.workspace = true
categories.workspace = true
description = "Visualization tools for StreamWeave"

[dependencies]
streamweave = { path = "../streamweave" }
serde = { workspace = true }
serde_json = { workspace = true }
tokio = { workspace = true, features = ["sync"] }

[dev-dependencies]
proptest = { workspace = true }

[features]
default = []
