[package]
name = "streamweave-producer-csv"
version = "0.3.0"
edition.workspace = true
authors.workspace = true
license.workspace = true
repository.workspace = true
homepage.workspace = true
documentation.workspace = true
keywords.workspace = true
categories.workspace = true
description = "CSV producer for StreamWeave"

[dependencies]
chrono = { workspace = true }
async-stream = { workspace = true }
streamweave = { path = "../../streamweave", version = "0.3.0" }
streamweave-error = { path = "../../error", version = "0.3.0" }
streamweave-message = { path = "../../message", version = "0.3.0", optional = true }
serde = { workspace = true }
csv = { workspace = true, optional = true }
tokio = { workspace = true, features = ["macros", "rt", "fs", "sync"] }
futures = { workspace = true }
async-trait = { workspace = true }
thiserror = { workspace = true }
tracing = { workspace = true }

[dev-dependencies]
tempfile = { workspace = true }

[features]
default = ["csv"]
csv = ["dep:csv"]
message-envelope = ["dep:streamweave-message"]
