[package]
name = "streamweave-csv"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true
repository = "https://github.com/Industrial/streamweave/tree/main/packages/csv"
homepage.workspace = true
documentation.workspace = true
keywords.workspace = true
categories.workspace = true
description = "Csv producer and consumer for StreamWeave"

[features]
default = ["csv"]
csv = ["dep:csv"]
message-envelope = ["dep:streamweave-message"]

[dependencies]
chrono = { workspace = true }
async-stream = { workspace = true }
streamweave = { path = "../streamweave" }
streamweave-error = { path = "../error" }
streamweave-message = { path = "../message", optional = true }
serde = { workspace = true }
csv = { workspace = true, optional = true }
tokio = { workspace = true, features = ["macros", "rt", "fs", "sync"] }
futures = { workspace = true }
async-trait = { workspace = true }
thiserror = { workspace = true }
tracing = { workspace = true }

[dev-dependencies.tempfile]
workspace = true

[dev-dependencies.proptest]
workspace = true

[[test]]
name = "csv_producer"
path = "test/csv_producer.rs"

[[test]]
name = "csv_consumer"
path = "test/csv_consumer.rs"
