[package]
name = "streamweave-csv"
version = "0.5.0"
edition.workspace = true
authors.workspace = true
license.workspace = true
repository = "https://github.com/Industrial/streamweave/tree/main/packages/csv"
homepage.workspace = true
documentation.workspace = true
keywords.workspace = true
categories.workspace = true
description = "Csv producer and consumer for StreamWeave"

[features]
default = ["csv"]
csv = ["dep:csv"]
message-envelope = ["dep:streamweave-message"]

[dependencies.chrono]
workspace = true

[dependencies.async-stream]
workspace = true

[dependencies.streamweave]
path = "../streamweave"
version = "0.5.0"

[dependencies.streamweave-error]
path = "../error"
version = "0.5.0"

[dependencies.streamweave-message]
path = "../message"
version = "0.5.0"
optional = true

[dependencies.serde]
workspace = true

[dependencies.csv]
workspace = true
optional = true

[dependencies.tokio]
workspace = true
features = ["macros", "rt", "fs", "sync"]

[dependencies.futures]
workspace = true

[dependencies.async-trait]
workspace = true

[dependencies.thiserror]
workspace = true

[dependencies.tracing]
workspace = true

[dev-dependencies.tempfile]
workspace = true

[dev-dependencies.proptest]
workspace = true

[[test]]
name = "csv_producer"
path = "test/csv_producer.rs"

[[test]]
name = "csv_consumer"
path = "test/csv_consumer.rs"
